from pptx import Presentation
from pptx.util import Inches, Pt
import os
from .config import OUTPUT_DIR

class SlideGenerator:
    def __init__(self):
        self.prs = Presentation()

    def add_title_slide(self, title, subtitle="Generated by Arabic Voice-to-Presentation"):
        """Adds a title slide to the presentation."""
        slide_layout = self.prs.slide_layouts[0]
        slide = self.prs.slides.add_slide(slide_layout)
        title_shape = slide.shapes.title
        subtitle_shape = slide.placeholders[1]
        
        title_shape.text = title
        subtitle_shape.text = subtitle

    def add_content_slide(self, title, bullet_points):
        """Adds a content slide with bullet points."""
        slide_layout = self.prs.slide_layouts[1]
        slide = self.prs.slides.add_slide(slide_layout)
        title_shape = slide.shapes.title
        body_shape = slide.placeholders[1]
        
        title_shape.text = title
        
        tf = body_shape.text_frame
        for point in bullet_points:
            p = tf.add_paragraph()
            p.text = point
            p.level = 0

    def create_presentation(self, slides_data, output_filename="presentation.pptx"):
        """Creates the full presentation from a list of slide data dictionaries."""
        if not slides_data or not isinstance(slides_data, list):
            print("Error: slides_data is empty or not a list.")
            return None
        
        try:
            # Re-initialize presentation for each call to avoid cumulative slides if reused
            self.prs = Presentation()
            
            # Add title slide if it's the first one or specifically marked
            for i, slide in enumerate(slides_data):
                if not isinstance(slide, dict):
                    print(f"Skipping invalid slide data at index {i}: {slide}")
                    continue
                    
                title = slide.get('title', 'Slide')
                
                if i == 0 or slide.get('type') == 'title':
                    subtitle = slide.get('subtitle', '')
                    self.add_title_slide(title, subtitle)
                else:
                    content = slide.get('content', [])
                    if isinstance(content, str): # Handle if LLM returns a single string instead of list
                        content = [content]
                    self.add_content_slide(title, content)
            
            os.makedirs(OUTPUT_DIR, exist_ok=True)
            output_path = os.path.join(OUTPUT_DIR, output_filename)
            self.prs.save(output_path)
            return output_path
        except Exception as e:
            print(f"Error creating PowerPoint: {e}")
            return None

# Example Usage
if __name__ == '__main__':
    generator = SlideGenerator()
    data = [
        {"title": "AI in Medicine", "subtitle": "How AI is changing healthcare", "type": "title"},
        {"title": "Applications", "content": ["Diagnosis", "Surgery", "Drug Discovery"]},
        {"title": "Challenges", "content": ["Data Privacy", "Algorithm Bias", "Ethical concerns"]}
    ]
    path = generator.create_presentation(data, "test_presentation.pptx")
    print(f"Presentation saved at: {path}")
