from pptx import Presentation
from pptx.util import Inches, Pt
import os
from .config import OUTPUT_DIR

class SlideGenerator:
    def __init__(self):
        self.prs = Presentation()

    def add_title_slide(self, title, subtitle="Generated by Arabic Voice-to-Presentation"):
        """Adds a title slide to the presentation."""
        slide_layout = self.prs.slide_layouts[0]
        slide = self.prs.slides.add_slide(slide_layout)
        title_shape = slide.shapes.title
        subtitle_shape = slide.placeholders[1]
        
        title_shape.text = title
        subtitle_shape.text = subtitle

    def add_content_slide(self, title, bullet_points):
        """Adds a content slide with bullet points."""
        slide_layout = self.prs.slide_layouts[1]
        slide = self.prs.slides.add_slide(slide_layout)
        title_shape = slide.shapes.title
        body_shape = slide.placeholders[1]
        
        title_shape.text = title
        
        tf = body_shape.text_frame
        for point in bullet_points:
            p = tf.add_paragraph()
            p.text = point
            p.level = 0

    def create_presentation(self, slides_data, output_filename="presentation.pptx"):
        """Creates the full presentation from a list of slide data dictionaries."""
        if not slides_data:
            return None
        
        # Add title slide if it's the first one or specifically marked
        for i, slide in enumerate(slides_data):
            if i == 0 or slide.get('type') == 'title':
                self.add_title_slide(slide.get('title', 'Presentation'), slide.get('subtitle', ''))
            else:
                self.add_content_slide(slide.get('title', 'Slide'), slide.get('content', []))
        
        output_path = os.path.join(OUTPUT_DIR, output_filename)
        self.prs.save(output_path)
        return output_path

# Example Usage
if __name__ == '__main__':
    generator = SlideGenerator()
    data = [
        {"title": "AI in Medicine", "subtitle": "How AI is changing healthcare", "type": "title"},
        {"title": "Applications", "content": ["Diagnosis", "Surgery", "Drug Discovery"]},
        {"title": "Challenges", "content": ["Data Privacy", "Algorithm Bias", "Ethical concerns"]}
    ]
    path = generator.create_presentation(data, "test_presentation.pptx")
    print(f"Presentation saved at: {path}")
